# Generated by Django 4.0.6 on 2022-07-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_posts_counter_dislikes_posts_counter_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='counter_dislikes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='counter_likes',
        ),
    ]
