# Generated by Django 4.0.6 on 2022-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_posts_counter_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='counter_dislikes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='counter_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
